### ISSUE TITLE
specifications of  Composition of Borated Water

### ISSUE THREAD

**Issue by rolandlenain** [mit-crpg/BEAVRS#3]
It seems that the formula page 145, (source 62) :
rho_Bh2o = h2o_dens / wB_Bh2o
is not correct (I use syntax of https://github.com/mit-crpg/BEAVRS/blob/master/models/openmc/beavrs/materials.py). 
according to your sources it should be :
rho_Bh2o = h2o_dens/(1 - wB_Bh2o)

**Comment by shikhar413** [comment]
Good catch @rolandlenain. I've gone ahead and updated the specifications with the correct formula
