### ISSUE TITLE
specifications of bp geometry : coherency between fig 9, 40

### ISSUE THREAD

**Issue by rolandlenain** [mit-crpg/BEAVRS#4]
In fig 9, external radius is guide tube at dashpot.
In fig 40, external radius is guide tube above dashpot for the zone described in fig 9.

is figure 9 wrong ?

**Comment by rolandlenain** [comment]
also fig 40 and fig 34 are not coherent: bare instrument tube is not present in the lowest extent in fig 40

**Comment by liangjg** [comment]
@rolandlenain Good catch!
- The outer radius of the BP plenum in figure 9 should be ORs of the guide tube above dashpot.
- The bare instrument tube should be down to the lowest extent as shown in figure 34.

I'll make some corrections.

**Comment by liangjg** [comment]
@rolandlenain Could you help take a look at the last [commit ](https://github.com/mit-crpg/BEAVRS/commit/7a9867014a2afec62201df1846de320e92f6a451)? Let me know if there is any problem.

**Comment by rolandlenain** [comment]
Il think also fig 38 has to be corrected with the lower part of the instrument.

**Comment by rolandlenain** [comment]
I wonder if the water density is correct in the nozzle (source 63) because it doesn't take into account the volume of the instrument rod for the lower part and the steel rods above the rods in the upper part

**Comment by rolandlenain** [comment]
also above the burnable absorber rods

**Comment by rolandlenain** [comment]
I found https://www.nrc.gov/docs/ML0335/ML033530020.pdf for ref 15 used in source 64. Is it correct?
reading Table 2-3 of [15] it seems that region 1 an 6 have steel inside (respectively 0.1770 and 0.1720). Why is there only water in these parts in figs 32-35?

also, lower nozzle seems to be more or less region 5 of Table 2-3 of [15] (according to elevation), for which steel fraction is 0.1439 and not 0.1720. Is 0.1720 really expected in source 64?

sorry for those questions. if they are not appropriate, just let me know.

**Comment by liangjg** [comment]
> Il think also fig 38 has to be corrected with the lower part of the instrument.

Thanks. Figure 38 was [updated](https://github.com/mit-crpg/BEAVRS/commit/6bf761178f0d4c7d486565cb99150f7e3c622446).

**Comment by liangjg** [comment]
> I wonder if the water density is correct in the nozzle (source 63) because it doesn't take into account the volume of the instrument rod for the lower part and the steel rods above the rods in the upper part



> also above the burnable absorber rods



> I found https://www.nrc.gov/docs/ML0335/ML033530020.pdf for ref 15 used in source 64. Is it correct?
> reading Table 2-3 of [15] it seems that region 1 an 6 have steel inside (respectively 0.1770 and 0.1720). Why is there only water in these parts in figs 32-35?
> 
> also, lower nozzle seems to be more or less region 5 of Table 2-3 of [15] (according to elevation), for which steel fraction is 0.1439 and not 0.1720. Is 0.1720 really expected in source 64?
> 
> sorry for those questions. if they are not appropriate, just let me know.


Thanks for your questions about the compositions/densities in the nozzle/support plate region. The approximations used may be improved by accounting for the volume of the extra rod, differentiating the nozzle and support plate... But I'm not sure how much they are affecting the simulation results. Have you done any testing before?
Anyway, I'll leave this as another issue. Please go ahead if you are interested to make the changes to [the openmc model](https://github.com/mit-crpg/BEAVRS/tree/master/models/openmc/beavrs), do some tests, and submit a PR.
